# Generated by Django 5.0 on 2023-12-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('FullStack', 'FullStack')], default=1),
            preserve_default=False,
        ),
    ]
