# Generated by Django 5.0 on 2023-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://mdbootstrap.com/img/new/avatars/6.jpg', null=True, upload_to='users/'),
        ),
    ]
