# Generated by Django 5.0 on 2023-12-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sertificate', models.FileField(upload_to='student-achivments/')),
                ('stipend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other', models.FileField(upload_to='student-achivments/')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')])),
            ],
        ),
        migrations.CreateModel(
            name='StudentParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=128)),
                ('father_date_of_birth', models.DateTimeField()),
                ('father_job', models.CharField(choices=[('actor', 'actor'), ('singer', 'singer'), ('detective', 'detective'), ('butcher', 'butcher'), ('programmer', 'programmer')])),
                ('mather_name', models.CharField(max_length=128)),
                ('mather_date_of_birth', models.DateTimeField()),
                ('mather_of_job', models.CharField(choices=[('norse', 'norse'), ('actress', 'actress')])),
            ],
        ),
        migrations.CreateModel(
            name='StudentSos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('relation_ship', models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('father', 'father'), ('mather', 'mather')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')])),
                ('notions', models.CharField(choices=[('Germany', 'Germany'), ('Spain', 'Spain'), ('Uzbekistan', 'Uzbekistan'), ('Tojikiston', 'Tojikiston')])),
                ('img', models.ImageField(upload_to='student-images/')),
                ('contract', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('process', 'process'), ('pending', 'pending'), ('success', 'success')], default='process')),
                ('achivments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achivments', to='students.achivments')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classes')),
                ('facultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultet.facultet')),
                ('parents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentparents')),
                ('call_sos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentsos')),
            ],
        ),
    ]
