# Generated by Django 5.0 on 2023-12-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('phone_num', models.CharField(max_length=12)),
                ('specs', models.CharField(choices=[('math', 'math'), ('geograpia', 'geograpia'), ('algebra', 'algebra')])),
                ('email', models.EmailField(max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='teachers/')),
            ],
        ),
    ]
